### ISSUE TITLE
This needs some restart option

### ISSUE THREAD

**Issue by Robdyx** [blopa/freedompop-telegram-bot#3]
Required something to restart the bot, or even an autorestart after the conversation is closed. Also a retry after a wrong username/password has been introduced.

**Comment by blopa** [comment]
Hey Robdyx! What do you mean with "something to restart the bot"? Like, admin-wise or user-wise? I'm working on a option for the user to remove it's account, and next I'll add the option to retry user/pass.

**Comment by Robdyx** [comment]
User-wise. That is exactly what I meant because right now if you enter a wrong password or change it in the service, there is no way to make the bot work again. Thank you!

**Comment by blopa** [comment]
The option to remove account is live now, I'm going to look into resending the password.

**Comment by blopa** [comment]
Okay, this will fix it: https://github.com/blopa/FreedomPop-Telegram-Bot/pull/5

It's live now. Can you give my project a star? That would help me a lot :D
